// Generated by Wrangler on Wed Jul 24 2024 18:48:58 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	PUBLIC_CHAT: KVNamespace;
	CLIENT_SECRET: string;
	CLIENT_SECRET_QA: string;
	CHATROOM: DurableObjectNamespace<import("./src/index").Chatroom>;
}
