#:schema node_modules/wrangler/config-schema.json

name = "chat-backend"
main = "src/index.ts"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

route = { pattern = "https://api.example.com/chat/v1/*", zone_name = "example.com" }

[[durable_objects.bindings]]
name = "CHATROOM"
class_name = "Chatroom"

[[migrations]]
tag = "v1"
new_classes = ["Chatroom"]

[[kv_namespaces]]
binding = "PUBLIC_CHAT"
id = "b988eb0a62bc4b6386987f81b05d1026"
